- name: Install emacs
  apt: name=emacs state=present

- name: Configure emacs
  sudo: no
  git: dest={{home}}/.emacs.d repo=https://github.com/rnjn/dotemacs.git update=no
  notify: Install emacs packages

